# Generated by Django 5.0.14 on 2026-07-08 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("page", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="professionals",
            name="experience",
            field=models.CharField(default="Expert", max_length=100),
        ),
    ]
