# Generated by Django 5.0.14 on 2026-07-09 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("page", "0002_professionals_experience"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="position",
            field=models.CharField(default="Employee", max_length=50),
        ),
    ]
