# Generated by Django 5.0.14 on 2026-07-09 07:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("page", "0002_professionals_experience"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="image",
            field=models.ImageField(null=True, upload_to="projects/"),
        ),
        migrations.AddField(
            model_name="post",
            name="name",
            field=models.CharField(default="N/A", max_length=50),
        ),
        migrations.AddField(
            model_name="post",
            name="position",
            field=models.CharField(default="Employee", max_length=50),
        ),
        migrations.AlterField(
            model_name="post",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
