# Generated by Django 5.0.14 on 2026-07-09 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("page", "0003_post_date_post_position"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="image",
            field=models.ImageField(default=1, upload_to="projects/"),
            preserve_default=False,
        ),
    ]
